# This file contains the configuration for the Brutalist Blog Generator

# The title of the blog, will be visible in the index page
title: "Brutalist Blog Generator"

# The tagline of the blog, will be visible in the index page
tagLine: "Because, often, less is more"

# The directory with the source files, posts must go in a subdirectory called "posts"
srcDir: "www"

# The directory where the generated files will be placed
outputDir: "dist"

# The public URL for the blog
siteUrl: "https://bettercallsaghul.com/brutalist-blog-generator"

# Links for the index page
links:
  - name: "Home"
    url: "/"

  - name: "GitHub"
    url: "https://github.com/saghul/brutalist-blog-generator"

  - name: "RSS"
    url: "rss.xml"

  - name: "About"
    url: "/pages/about.html"

# Footer for all pages
footer: "© Saúl Ibarra Corretgé"

# Theme configuration
#theme:
#  light:
#    background: "#FAFAFA"
#    text: "#24292f"
#    link: "#0969da"
#    codeBg: "#f6f8fa"
#    border: "#d0d7de"
#    codeBorderLeft: "#2b2b2b"
#    secondaryText: "#57606a"
#  dark:
#    background: "#0d1117"
#    text: "#e6edf3"
#    link: "#58a6ff"
#    codeBg: "#161b22"
#    border: "#30363d"
#    codeBorderLeft: "#6e7681"
#    secondaryText: "#8b949e"

# Default theme: "light", "dark", or "auto" (respects system preference)
#defaultTheme: "auto"
