name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift --version
      - run: make
      - run: make test
      - run: make release
      - run: .build/release/bbg build
  build-linux:
    runs-on: ubuntu-latest
    container: swift:6.0-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: swift --version
      - run: apt update && apt install -y build-essential make
      - run: make
      - run: make test
      - run: make release
      - run: .build/release/bbg build
